# Generated by Django 2.2.1 on 2020-03-31 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRerquest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_name', models.CharField(max_length=250)),
                ('visitor_email', models.EmailField(max_length=250)),
                ('visitor_phone', models.CharField(max_length=14)),
                ('service_type', models.CharField(choices=[('none', 'Select a service'), ('Logo', 'Logo (Inkscape, GIMP)'), ('Word', 'Document preparation (Word)'), ('LaTex', 'Document preparation (LaTex)'), ('Web_app', 'Web application (Django)')], default='none', max_length=7)),
                ('service_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
