# Generated by Django 2.2.1 on 2020-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('None', 'Select a service'), ('Teaching', 'Teaching (Secondary, University)'), ('Logo Design', 'Logo & graphics Design'), ('Document preparation (Word)', 'Document preparation (Word)'), ('Document preparation LaTex', 'Document preparation (LaTex)'), ('Web application (Django)', 'Web application (Django)')], default='None', max_length=50),
        ),
    ]
