# Generated by Django 2.2.1 on 2020-04-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_auto_20200401_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('None', 'Select a service'), ('Logo design', 'Logo (Inkscape, GIMP)'), ('Document preparation (Word)', 'Document preparation (Word)'), ('Document preparation (LaTex)', 'Document preparation (LaTex)'), ('Web application', 'Web application (Django)')], default='none', max_length=7),
        ),
    ]
