# Generated by Django 2.2.1 on 2020-04-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_auto_20200402_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('None', 'Select a service'), ('Logo', 'Logo, Design'), ('Word Doc', 'Document preparation (Word)'), ('LaTex Doc', 'Document preparation (LaTex)'), ('Web app', 'Web application (Django)')], default='None', max_length=7),
        ),
    ]
