# Generated by Django 2.2.1 on 2020-05-08 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor_name', models.CharField(max_length=250)),
                ('visitor_email', models.EmailField(blank=True, max_length=250)),
                ('visitor_phone', models.CharField(blank=True, max_length=14)),
                ('message_subject', models.CharField(max_length=250)),
                ('message_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
