# Generated by Django 2.2.1 on 2020-05-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_visitormessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitormessage',
            old_name='message_description',
            new_name='message_text',
        ),
    ]
