# Generated by Django 2.2.1 on 2020-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200508_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject_types',
            field=models.CharField(choices=[('Phy', 'Physics'), ('Prog', 'Programming'), ('Django', 'Django'), ('Learn', 'Learning'), ('Tec', 'Tec talk')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
