# Generated by Django 2.2.1 on 2020-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200517_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject_types',
            field=models.CharField(choices=[('None', 'select subject'), ('Physics', 'Physics'), ('Programming', 'Programming'), ('Django', 'Django'), ('Learning', 'Learning'), ('Tec talk', 'Tec talk'), ('Personal', 'Personal')], default='None', max_length=50),
        ),
    ]
